spring:
  application:
    name: customerportallibrary
  datasource:
    username: root
    url: http://localhost:3307/customerportallibrary
    password: root
  jpa:
    generate-ddl: false  
  
management:
  endpoints:
    web:
      exposure:
        include: refresh
        
senior:
  citizen: Jadooo
junior:
  citizen: Jaddi
  

  